name: magic_dropdown
description: A flutter dropdown widget with highly customizable options. Render a custom child in your dropdown menu with custom sizings, customize the button to your own needs and experience a fully responsive dropdown menu!

version: 1.1.0+2
homepage: https://github.com/Bassiuz/magic_dropdown/

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  transparent_pointer: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true